### ISSUE TITLE
fix cops in theforeman-rubocop users

### ISSUE THREAD

**Issue by archanaserver** [theforeman/theforeman-rubocop#10]
- [x] https://github.com/theforeman/foreman_remote_execution/pull/848
- [x] https://github.com/theforeman/foreman_maintain/pull/789
- [x] https://github.com/theforeman/ldap_fluff/pull/74
- [x] https://github.com/theforeman/foreman_discovery/pull/614
- [x] https://github.com/theforeman/puppetdb_foreman/pull/85
- [x] https://github.com/theforeman/foreman_salt/pull/191
- [x] https://github.com/theforeman/foreman_bootdisk/pull/153
- [x] https://github.com/theforeman/foreman_puppet/pull/380
- [x] https://github.com/theforeman/foreman_fog_proxmox/pull/330
- [x] https://github.com/theforeman/foreman_google/pull/73
- [x] https://github.com/theforeman/foreman_leapp/pull/141
- [x] https://github.com/theforeman/foreman_templates/pull/185

**Comment by ehelms** [comment]
All associated PRs are now closed, thanks @archanaserver for driving this!
